[package]
name = "export-roam-notes"
version = "0.2.3"
authors = ["Daniel Imfeld <daniel@imfeld.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
chrono = "0.4.19"
dotenv = "0.15.0"
edn-rs = "0.16.12"
fxhash = "0.2.1"
handlebars = "3.5.2"
itertools = "0.10.0"
katex = "0.3.2"
nom = "6.0.1"
rayon = "1.5.0"
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.61"
smallvec = "1.6.1"
structopt = "0.3.21"
syntect = "4.5.0"
toml = "0.5.8"
urlocator = "0.1.4"
zip = "0.5.9"
