[package]
name = "export-roam-notes"
version = "0.1.0"
authors = ["Daniel Imfeld <daniel@imfeld.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
dotenv = "0.15.0"
edn-rs = "0.16.12"
fxhash = "0.2.1"
itertools = "0.10.0"
nom = "6.0.1"
percent-encoding = "2.1.0"
rayon = "1.5.0"
serde = "1.0.118"
serde_json = "1.0.61"
smallvec = "1.6.1"
structopt = "0.3.21"
syntect = "4.5.0"
toml = "0.5.8"
zip = "0.5.9"
